/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c Adaptor -a adaptor.h:adaptor.cpp com.contact.info.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include "contactinfo.h"
/*
 * Implementation of adaptor class Adaptor
 */

Adaptor::Adaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

Adaptor::~Adaptor()
{
    // destructor
}

contactList Adaptor::GetContactDetails()
{
    // handle method call com.contact.info.GetContactDetails
    contactList list;
    QMetaObject::invokeMethod(parent(), "GetContactDetails", Q_RETURN_ARG(contactList, list));
    return list;
}

